#! usr/bin/env bash

# --------------
# SPOTIFYD SETUP
# --------------

sudo -v # validate as sudo

read -p "Enter your spotify password: " SPOTIFY_PASSWORD

echo "Installing spotifyd..."
wget "https://github.com/Spotifyd/spotifyd/releases/download/v0.3.4/spotifyd-linux-armv6-slim.tar.gz" && # download
    tar xzf spotifyd-linux-armv6*.tar.gz &&                                                              # unpack
    sudo cp ./spotifyd /usr/bin/spotifyd                                                                 # add to bin

echo "Creating launch service..."
# create launch service file
sudo touch /etc/systemd/user/spotifyd.service
curl "https://raw.githubusercontent.com/Spotifyd/spotifyd/master/contrib/spotifyd.service" | sudo tee /etc/systemd/user/spotifyd.service

# enable launch service at launch
sudo loginctl enable-linger $(whoami)
systemctl --user enable spotifyd.service

echo "Creating configuration file..."
# create config file
mkdir -p ~/.config/spotifyd/
touch ~/.config/spotifyd/spotifyd.conf

# copy config file with password inserted
printf "$(cat ./spotifyd/spotifyd.conf)" $SPOTIFY_PASSWORD > \
    ~/.config/spotifyd/spotifyd.conf

echo "Cleaning up..."
rm spotifyd-linux-armv6*
rm spotifyd

echo "Starting spotifyd..."
systemctl --user start spotifyd.service

echo "done!"
